name: athfal
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.0
  carousel_pro: ^1.0.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Comic
      fonts:
      - asset: assets/fonts/cmsbold.ttf
      - asset: assets/fonts/cmsreguler.ttf